# ------------------------------------------------------------------------------
# More resources related to this file:
# [1] Overview   | https://docs.docker.com/compose/
# [2] PostgreSQL | https://github.com/docker-library/docs/tree/master/postgres
# [3] Node.js    | https://github.com/nodejs/docker-node/blob/master/README.md#how-to-use-this-image
# -------------
#  More resources for your projects:\





services:
  heroku-cli:
    build: ./heroku
    env_file: ./heroku/.env
  # ------------------------------------------- # This section defines our Node.js image [3].
  db:
    build: ./db
    env_file: .env
    volumes:
      - ./db/init_data:/docker-entrypoint-initdb.d
      - proj-db-volume:/var/lib/postgresql/data
      
  web:
    build:
      context: ./
      dockerfile: Dockerfile
      target: devapp
    depends_on:
      - db
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
volumes:
  proj-db-volume: {}                                         # update in real time.
